// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-wPKaBy9UJm_qImGh_M5P6icDVlYEIU0',
    appId: '1:509729442271:web:e5d0afa1bf5a4bbbc2dc6a',
    messagingSenderId: '509729442271',
    projectId: 'doctor-finder-f66db',
    authDomain: 'doctor-finder-f66db.firebaseapp.com',
    storageBucket: 'doctor-finder-f66db.firebasestorage.app',
    measurementId: 'G-PMMH0FZ9YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4JwPOJJTJY9UWGNtIwmn9lfQHBRWGy_M',
    appId: '1:509729442271:android:b8f7798770d0a12bc2dc6a',
    messagingSenderId: '509729442271',
    projectId: 'doctor-finder-f66db',
    storageBucket: 'doctor-finder-f66db.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlT9DQZf2qrd5Eqzy1-7cdKGnrc23JdkE',
    appId: '1:509729442271:ios:27124defbd3f08f2c2dc6a',
    messagingSenderId: '509729442271',
    projectId: 'doctor-finder-f66db',
    storageBucket: 'doctor-finder-f66db.firebasestorage.app',
    iosBundleId: 'com.example.doctorFinder',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlT9DQZf2qrd5Eqzy1-7cdKGnrc23JdkE',
    appId: '1:509729442271:ios:27124defbd3f08f2c2dc6a',
    messagingSenderId: '509729442271',
    projectId: 'doctor-finder-f66db',
    storageBucket: 'doctor-finder-f66db.firebasestorage.app',
    iosBundleId: 'com.example.doctorFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-wPKaBy9UJm_qImGh_M5P6icDVlYEIU0',
    appId: '1:509729442271:web:48a99c728407f84ec2dc6a',
    messagingSenderId: '509729442271',
    projectId: 'doctor-finder-f66db',
    authDomain: 'doctor-finder-f66db.firebaseapp.com',
    storageBucket: 'doctor-finder-f66db.firebasestorage.app',
    measurementId: 'G-3472DPKYSF',
  );
}
